name: ETL Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
    - name: Use secret in environment variable
      env:
        API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}  
          
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        
    - name: Run ETL pipeline
      run: |
        python extract.py > extracted.json
        python transform.py < extracted.json > transformed.json
        python load.py < transformed.json
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        
    - name: Upload output artifact
      uses: actions/upload-artifact@v3
      with:
        name: weather-data
        path: weather_data.csv